### ISSUE TITLE
Battery/date overlap

### ISSUE THREAD

**Issue by ghost** [smirko-dev/fitbit-clockface#21]
![060AB017-C15D-4E41-AF88-C5204AD7ED36](https://user-images.githubusercontent.com/96164644/146131293-4afe0ddf-7bbd-4084-a39f-fd77d5fcc683.jpeg)
 
 the date and the battery icon are overlapping. And I cant fogure out how to remove either?

**Comment by smirko-dev** [comment]
Hi @Martiebi 
thx for your feedback. I'll think about a solution. Which watch do you use?

**Comment by ghost** [comment]
Hi! I have a Versa 3

**Comment by smirko-dev** [comment]
Okay, thanks.
But I can't promise a solution soon, since I'm busy.
Maybe closer to the end of the year or January.

**Comment by smirko-dev** [comment]
Solved with version 1.7
